// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v5.29.3
// source: clouddrive.proto

package clouddrivepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OfflineFileStatus int32

const (
	OfflineFileStatus_OFFLINE_INIT        OfflineFileStatus = 0
	OfflineFileStatus_OFFLINE_DOWNLOADING OfflineFileStatus = 1
	OfflineFileStatus_OFFLINE_FINISHED    OfflineFileStatus = 2
	OfflineFileStatus_OFFLINE_ERROR       OfflineFileStatus = 3
	OfflineFileStatus_OFFLINE_UNKNOWN     OfflineFileStatus = 4
)

// Enum value maps for OfflineFileStatus.
var (
	OfflineFileStatus_name = map[int32]string{
		0: "OFFLINE_INIT",
		1: "OFFLINE_DOWNLOADING",
		2: "OFFLINE_FINISHED",
		3: "OFFLINE_ERROR",
		4: "OFFLINE_UNKNOWN",
	}
	OfflineFileStatus_value = map[string]int32{
		"OFFLINE_INIT":        0,
		"OFFLINE_DOWNLOADING": 1,
		"OFFLINE_FINISHED":    2,
		"OFFLINE_ERROR":       3,
		"OFFLINE_UNKNOWN":     4,
	}
)

func (x OfflineFileStatus) Enum() *OfflineFileStatus {
	p := new(OfflineFileStatus)
	*p = x
	return p
}

func (x OfflineFileStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OfflineFileStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_clouddrive_proto_enumTypes[0].Descriptor()
}

func (OfflineFileStatus) Type() protoreflect.EnumType {
	return &file_clouddrive_proto_enumTypes[0]
}

func (x OfflineFileStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OfflineFileStatus.Descriptor instead.
func (OfflineFileStatus) EnumDescriptor() ([]byte, []int) {
	return file_clouddrive_proto_rawDescGZIP(), []int{0}
}

type CloudDriveFile_FileType int32

const (
	CloudDriveFile_Directory CloudDriveFile_FileType = 0
	CloudDriveFile_File      CloudDriveFile_FileType = 1
	CloudDriveFile_Other     CloudDriveFile_FileType = 2
)

// Enum value maps for CloudDriveFile_FileType.
var (
	CloudDriveFile_FileType_name = map[int32]string{
		0: "Directory",
		1: "File",
		2: "Other",
	}
	CloudDriveFile_FileType_value = map[string]int32{
		"Directory": 0,
		"File":      1,
		"Other":     2,
	}
)

func (x CloudDriveFile_FileType) Enum() *CloudDriveFile_FileType {
	p := new(CloudDriveFile_FileType)
	*p = x
	return p
}

func (x CloudDriveFile_FileType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CloudDriveFile_FileType) Descriptor() protoreflect.EnumDescriptor {
	return file_clouddrive_proto_enumTypes[1].Descriptor()
}

func (CloudDriveFile_FileType) Type() protoreflect.EnumType {
	return &file_clouddrive_proto_enumTypes[1]
}

func (x CloudDriveFile_FileType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CloudDriveFile_FileType.Descriptor instead.
func (CloudDriveFile_FileType) EnumDescriptor() ([]byte, []int) {
	return file_clouddrive_proto_rawDescGZIP(), []int{12, 0}
}

type StringValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringValue) Reset() {
	*x = StringValue{}
	mi := &file_clouddrive_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringValue) ProtoMessage() {}

func (x *StringValue) ProtoReflect() protoreflect.Message {
	mi := &file_clouddrive_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringValue.ProtoReflect.Descriptor instead.
func (*StringValue) Descriptor() ([]byte, []int) {
	return file_clouddrive_proto_rawDescGZIP(), []int{0}
}

func (x *StringValue) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type CloudDriveSystemInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsLogin       bool                   `protobuf:"varint,1,opt,name=IsLogin,proto3" json:"IsLogin,omitempty"`
	UserName      string                 `protobuf:"bytes,2,opt,name=UserName,proto3" json:"UserName,omitempty"`
	SystemReady   bool                   `protobuf:"varint,3,opt,name=SystemReady,proto3" json:"SystemReady,omitempty"`
	SystemMessage *string                `protobuf:"bytes,4,opt,name=SystemMessage,proto3,oneof" json:"SystemMessage,omitempty"`
	HasError      *bool                  `protobuf:"varint,5,opt,name=hasError,proto3,oneof" json:"hasError,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloudDriveSystemInfo) Reset() {
	*x = CloudDriveSystemInfo{}
	mi := &file_clouddrive_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloudDriveSystemInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloudDriveSystemInfo) ProtoMessage() {}

func (x *CloudDriveSystemInfo) ProtoReflect() protoreflect.Message {
	mi := &file_clouddrive_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloudDriveSystemInfo.ProtoReflect.Descriptor instead.
func (*CloudDriveSystemInfo) Descriptor() ([]byte, []int) {
	return file_clouddrive_proto_rawDescGZIP(), []int{1}
}

func (x *CloudDriveSystemInfo) GetIsLogin() bool {
	if x != nil {
		return x.IsLogin
	}
	return false
}

func (x *CloudDriveSystemInfo) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *CloudDriveSystemInfo) GetSystemReady() bool {
	if x != nil {
		return x.SystemReady
	}
	return false
}

func (x *CloudDriveSystemInfo) GetSystemMessage() string {
	if x != nil && x.SystemMessage != nil {
		return *x.SystemMessage
	}
	return ""
}

func (x *CloudDriveSystemInfo) GetHasError() bool {
	if x != nil && x.HasError != nil {
		return *x.HasError
	}
	return false
}

type TokenPermissions struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	AllowList                 bool                   `protobuf:"varint,1,opt,name=allow_list,json=allowList,proto3" json:"allow_list,omitempty"`
	AllowCreateFolder         bool                   `protobuf:"varint,4,opt,name=allow_create_folder,json=allowCreateFolder,proto3" json:"allow_create_folder,omitempty"`
	AllowRead                 bool                   `protobuf:"varint,7,opt,name=allow_read,json=allowRead,proto3" json:"allow_read,omitempty"`
	AllowAddOfflineDownload   bool                   `protobuf:"varint,16,opt,name=allow_add_offline_download,json=allowAddOfflineDownload,proto3" json:"allow_add_offline_download,omitempty"`
	AllowListOfflineDownloads bool                   `protobuf:"varint,17,opt,name=allow_list_offline_downloads,json=allowListOfflineDownloads,proto3" json:"allow_list_offline_downloads,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *TokenPermissions) Reset() {
	*x = TokenPermissions{}
	mi := &file_clouddrive_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenPermissions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenPermissions) ProtoMessage() {}

func (x *TokenPermissions) ProtoReflect() protoreflect.Message {
	mi := &file_clouddrive_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenPermissions.ProtoReflect.Descriptor instead.
func (*TokenPermissions) Descriptor() ([]byte, []int) {
	return file_clouddrive_proto_rawDescGZIP(), []int{2}
}

func (x *TokenPermissions) GetAllowList() bool {
	if x != nil {
		return x.AllowList
	}
	return false
}

func (x *TokenPermissions) GetAllowCreateFolder() bool {
	if x != nil {
		return x.AllowCreateFolder
	}
	return false
}

func (x *TokenPermissions) GetAllowRead() bool {
	if x != nil {
		return x.AllowRead
	}
	return false
}

func (x *TokenPermissions) GetAllowAddOfflineDownload() bool {
	if x != nil {
		return x.AllowAddOfflineDownload
	}
	return false
}

func (x *TokenPermissions) GetAllowListOfflineDownloads() bool {
	if x != nil {
		return x.AllowListOfflineDownloads
	}
	return false
}

type TokenInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	RootDir       string                 `protobuf:"bytes,2,opt,name=rootDir,proto3" json:"rootDir,omitempty"`
	Permissions   *TokenPermissions      `protobuf:"bytes,3,opt,name=permissions,proto3" json:"permissions,omitempty"`
	ExpiresIn     *uint64                `protobuf:"varint,4,opt,name=expires_in,json=expiresIn,proto3,oneof" json:"expires_in,omitempty"`
	FriendlyName  string                 `protobuf:"bytes,5,opt,name=friendly_name,json=friendlyName,proto3" json:"friendly_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenInfo) Reset() {
	*x = TokenInfo{}
	mi := &file_clouddrive_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenInfo) ProtoMessage() {}

func (x *TokenInfo) ProtoReflect() protoreflect.Message {
	mi := &file_clouddrive_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenInfo.ProtoReflect.Descriptor instead.
func (*TokenInfo) Descriptor() ([]byte, []int) {
	return file_clouddrive_proto_rawDescGZIP(), []int{3}
}

func (x *TokenInfo) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *TokenInfo) GetRootDir() string {
	if x != nil {
		return x.RootDir
	}
	return ""
}

func (x *TokenInfo) GetPermissions() *TokenPermissions {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *TokenInfo) GetExpiresIn() uint64 {
	if x != nil && x.ExpiresIn != nil {
		return *x.ExpiresIn
	}
	return 0
}

func (x *TokenInfo) GetFriendlyName() string {
	if x != nil {
		return x.FriendlyName
	}
	return ""
}

type FileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	ForceRefresh  *bool                  `protobuf:"varint,2,opt,name=forceRefresh,proto3,oneof" json:"forceRefresh,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileRequest) Reset() {
	*x = FileRequest{}
	mi := &file_clouddrive_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileRequest) ProtoMessage() {}

func (x *FileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clouddrive_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileRequest.ProtoReflect.Descriptor instead.
func (*FileRequest) Descriptor() ([]byte, []int) {
	return file_clouddrive_proto_rawDescGZIP(), []int{4}
}

func (x *FileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileRequest) GetForceRefresh() bool {
	if x != nil && x.ForceRefresh != nil {
		return *x.ForceRefresh
	}
	return false
}

type FileOperationResult struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Success         bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage    string                 `protobuf:"bytes,2,opt,name=errorMessage,proto3" json:"errorMessage,omitempty"`
	ResultFilePaths []string               `protobuf:"bytes,3,rep,name=resultFilePaths,proto3" json:"resultFilePaths,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FileOperationResult) Reset() {
	*x = FileOperationResult{}
	mi := &file_clouddrive_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileOperationResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileOperationResult) ProtoMessage() {}

func (x *FileOperationResult) ProtoReflect() protoreflect.Message {
	mi := &file_clouddrive_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileOperationResult.ProtoReflect.Descriptor instead.
func (*FileOperationResult) Descriptor() ([]byte, []int) {
	return file_clouddrive_proto_rawDescGZIP(), []int{5}
}

func (x *FileOperationResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *FileOperationResult) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *FileOperationResult) GetResultFilePaths() []string {
	if x != nil {
		return x.ResultFilePaths
	}
	return nil
}

type AddOfflineFileRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Urls                 string                 `protobuf:"bytes,1,opt,name=urls,proto3" json:"urls,omitempty"`
	ToFolder             string                 `protobuf:"bytes,2,opt,name=toFolder,proto3" json:"toFolder,omitempty"`
	CheckFolderAfterSecs *uint64                `protobuf:"varint,3,opt,name=checkFolderAfterSecs,proto3,oneof" json:"checkFolderAfterSecs,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *AddOfflineFileRequest) Reset() {
	*x = AddOfflineFileRequest{}
	mi := &file_clouddrive_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddOfflineFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddOfflineFileRequest) ProtoMessage() {}

func (x *AddOfflineFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clouddrive_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddOfflineFileRequest.ProtoReflect.Descriptor instead.
func (*AddOfflineFileRequest) Descriptor() ([]byte, []int) {
	return file_clouddrive_proto_rawDescGZIP(), []int{6}
}

func (x *AddOfflineFileRequest) GetUrls() string {
	if x != nil {
		return x.Urls
	}
	return ""
}

func (x *AddOfflineFileRequest) GetToFolder() string {
	if x != nil {
		return x.ToFolder
	}
	return ""
}

func (x *AddOfflineFileRequest) GetCheckFolderAfterSecs() uint64 {
	if x != nil && x.CheckFolderAfterSecs != nil {
		return *x.CheckFolderAfterSecs
	}
	return 0
}

type ListSubFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	ForceRefresh  bool                   `protobuf:"varint,2,opt,name=forceRefresh,proto3" json:"forceRefresh,omitempty"`
	CheckExpires  *bool                  `protobuf:"varint,3,opt,name=checkExpires,proto3,oneof" json:"checkExpires,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSubFileRequest) Reset() {
	*x = ListSubFileRequest{}
	mi := &file_clouddrive_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSubFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSubFileRequest) ProtoMessage() {}

func (x *ListSubFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clouddrive_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSubFileRequest.ProtoReflect.Descriptor instead.
func (*ListSubFileRequest) Descriptor() ([]byte, []int) {
	return file_clouddrive_proto_rawDescGZIP(), []int{7}
}

func (x *ListSubFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ListSubFileRequest) GetForceRefresh() bool {
	if x != nil {
		return x.ForceRefresh
	}
	return false
}

func (x *ListSubFileRequest) GetCheckExpires() bool {
	if x != nil && x.CheckExpires != nil {
		return *x.CheckExpires
	}
	return false
}

type SubFilesReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SubFiles      []*CloudDriveFile      `protobuf:"bytes,1,rep,name=subFiles,proto3" json:"subFiles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubFilesReply) Reset() {
	*x = SubFilesReply{}
	mi := &file_clouddrive_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubFilesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubFilesReply) ProtoMessage() {}

func (x *SubFilesReply) ProtoReflect() protoreflect.Message {
	mi := &file_clouddrive_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubFilesReply.ProtoReflect.Descriptor instead.
func (*SubFilesReply) Descriptor() ([]byte, []int) {
	return file_clouddrive_proto_rawDescGZIP(), []int{8}
}

func (x *SubFilesReply) GetSubFiles() []*CloudDriveFile {
	if x != nil {
		return x.SubFiles
	}
	return nil
}

type FindFileByPathRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParentPath    string                 `protobuf:"bytes,1,opt,name=parentPath,proto3" json:"parentPath,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindFileByPathRequest) Reset() {
	*x = FindFileByPathRequest{}
	mi := &file_clouddrive_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindFileByPathRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindFileByPathRequest) ProtoMessage() {}

func (x *FindFileByPathRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clouddrive_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindFileByPathRequest.ProtoReflect.Descriptor instead.
func (*FindFileByPathRequest) Descriptor() ([]byte, []int) {
	return file_clouddrive_proto_rawDescGZIP(), []int{9}
}

func (x *FindFileByPathRequest) GetParentPath() string {
	if x != nil {
		return x.ParentPath
	}
	return ""
}

func (x *FindFileByPathRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type CreateFolderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParentPath    string                 `protobuf:"bytes,1,opt,name=parentPath,proto3" json:"parentPath,omitempty"`
	FolderName    string                 `protobuf:"bytes,2,opt,name=folderName,proto3" json:"folderName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFolderRequest) Reset() {
	*x = CreateFolderRequest{}
	mi := &file_clouddrive_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFolderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFolderRequest) ProtoMessage() {}

func (x *CreateFolderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clouddrive_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFolderRequest.ProtoReflect.Descriptor instead.
func (*CreateFolderRequest) Descriptor() ([]byte, []int) {
	return file_clouddrive_proto_rawDescGZIP(), []int{10}
}

func (x *CreateFolderRequest) GetParentPath() string {
	if x != nil {
		return x.ParentPath
	}
	return ""
}

func (x *CreateFolderRequest) GetFolderName() string {
	if x != nil {
		return x.FolderName
	}
	return ""
}

type CreateFolderResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FolderCreated *CloudDriveFile        `protobuf:"bytes,1,opt,name=folderCreated,proto3" json:"folderCreated,omitempty"`
	Result        *FileOperationResult   `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFolderResult) Reset() {
	*x = CreateFolderResult{}
	mi := &file_clouddrive_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFolderResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFolderResult) ProtoMessage() {}

func (x *CreateFolderResult) ProtoReflect() protoreflect.Message {
	mi := &file_clouddrive_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFolderResult.ProtoReflect.Descriptor instead.
func (*CreateFolderResult) Descriptor() ([]byte, []int) {
	return file_clouddrive_proto_rawDescGZIP(), []int{11}
}

func (x *CreateFolderResult) GetFolderCreated() *CloudDriveFile {
	if x != nil {
		return x.FolderCreated
	}
	return nil
}

func (x *CreateFolderResult) GetResult() *FileOperationResult {
	if x != nil {
		return x.Result
	}
	return nil
}

type CloudDriveFile struct {
	state                            protoimpl.MessageState  `protogen:"open.v1"`
	Id                               string                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                             string                  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	FullPathName                     string                  `protobuf:"bytes,3,opt,name=fullPathName,proto3" json:"fullPathName,omitempty"`
	Size                             int64                   `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	FileType                         CloudDriveFile_FileType `protobuf:"varint,5,opt,name=fileType,proto3,enum=clouddrive.CloudDriveFile_FileType" json:"fileType,omitempty"`
	CreateTime                       *timestamppb.Timestamp  `protobuf:"bytes,6,opt,name=createTime,proto3" json:"createTime,omitempty"`
	WriteTime                        *timestamppb.Timestamp  `protobuf:"bytes,7,opt,name=writeTime,proto3" json:"writeTime,omitempty"`
	IsDirectory                      bool                    `protobuf:"varint,30,opt,name=isDirectory,proto3" json:"isDirectory,omitempty"`
	IsRoot                           bool                    `protobuf:"varint,31,opt,name=isRoot,proto3" json:"isRoot,omitempty"`
	IsCloudRoot                      bool                    `protobuf:"varint,32,opt,name=isCloudRoot,proto3" json:"isCloudRoot,omitempty"`
	IsCloudDirectory                 bool                    `protobuf:"varint,33,opt,name=isCloudDirectory,proto3" json:"isCloudDirectory,omitempty"`
	IsCloudFile                      bool                    `protobuf:"varint,34,opt,name=isCloudFile,proto3" json:"isCloudFile,omitempty"`
	IsLocal                          bool                    `protobuf:"varint,37,opt,name=isLocal,proto3" json:"isLocal,omitempty"`
	CanOfflineDownload               bool                    `protobuf:"varint,66,opt,name=canOfflineDownload,proto3" json:"canOfflineDownload,omitempty"`
	SupportOfflineDownloadManagement bool                    `protobuf:"varint,75,opt,name=supportOfflineDownloadManagement,proto3" json:"supportOfflineDownloadManagement,omitempty"`
	ReadOnly                         bool                    `protobuf:"varint,80,opt,name=readOnly,proto3" json:"readOnly,omitempty"`
	unknownFields                    protoimpl.UnknownFields
	sizeCache                        protoimpl.SizeCache
}

func (x *CloudDriveFile) Reset() {
	*x = CloudDriveFile{}
	mi := &file_clouddrive_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloudDriveFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloudDriveFile) ProtoMessage() {}

func (x *CloudDriveFile) ProtoReflect() protoreflect.Message {
	mi := &file_clouddrive_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloudDriveFile.ProtoReflect.Descriptor instead.
func (*CloudDriveFile) Descriptor() ([]byte, []int) {
	return file_clouddrive_proto_rawDescGZIP(), []int{12}
}

func (x *CloudDriveFile) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CloudDriveFile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CloudDriveFile) GetFullPathName() string {
	if x != nil {
		return x.FullPathName
	}
	return ""
}

func (x *CloudDriveFile) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *CloudDriveFile) GetFileType() CloudDriveFile_FileType {
	if x != nil {
		return x.FileType
	}
	return CloudDriveFile_Directory
}

func (x *CloudDriveFile) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *CloudDriveFile) GetWriteTime() *timestamppb.Timestamp {
	if x != nil {
		return x.WriteTime
	}
	return nil
}

func (x *CloudDriveFile) GetIsDirectory() bool {
	if x != nil {
		return x.IsDirectory
	}
	return false
}

func (x *CloudDriveFile) GetIsRoot() bool {
	if x != nil {
		return x.IsRoot
	}
	return false
}

func (x *CloudDriveFile) GetIsCloudRoot() bool {
	if x != nil {
		return x.IsCloudRoot
	}
	return false
}

func (x *CloudDriveFile) GetIsCloudDirectory() bool {
	if x != nil {
		return x.IsCloudDirectory
	}
	return false
}

func (x *CloudDriveFile) GetIsCloudFile() bool {
	if x != nil {
		return x.IsCloudFile
	}
	return false
}

func (x *CloudDriveFile) GetIsLocal() bool {
	if x != nil {
		return x.IsLocal
	}
	return false
}

func (x *CloudDriveFile) GetCanOfflineDownload() bool {
	if x != nil {
		return x.CanOfflineDownload
	}
	return false
}

func (x *CloudDriveFile) GetSupportOfflineDownloadManagement() bool {
	if x != nil {
		return x.SupportOfflineDownloadManagement
	}
	return false
}

func (x *CloudDriveFile) GetReadOnly() bool {
	if x != nil {
		return x.ReadOnly
	}
	return false
}

type OfflineFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Size          uint64                 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	Status        OfflineFileStatus      `protobuf:"varint,4,opt,name=status,proto3,enum=clouddrive.OfflineFileStatus" json:"status,omitempty"`
	InfoHash      string                 `protobuf:"bytes,5,opt,name=infoHash,proto3" json:"infoHash,omitempty"`
	FileId        string                 `protobuf:"bytes,6,opt,name=fileId,proto3" json:"fileId,omitempty"`
	AddTime       uint64                 `protobuf:"varint,7,opt,name=add_time,json=addTime,proto3" json:"add_time,omitempty"`
	ParentId      string                 `protobuf:"bytes,8,opt,name=parentId,proto3" json:"parentId,omitempty"`
	PercendDone   float64                `protobuf:"fixed64,9,opt,name=percendDone,proto3" json:"percendDone,omitempty"`
	Peers         uint64                 `protobuf:"varint,10,opt,name=peers,proto3" json:"peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OfflineFile) Reset() {
	*x = OfflineFile{}
	mi := &file_clouddrive_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OfflineFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OfflineFile) ProtoMessage() {}

func (x *OfflineFile) ProtoReflect() protoreflect.Message {
	mi := &file_clouddrive_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OfflineFile.ProtoReflect.Descriptor instead.
func (*OfflineFile) Descriptor() ([]byte, []int) {
	return file_clouddrive_proto_rawDescGZIP(), []int{13}
}

func (x *OfflineFile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OfflineFile) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *OfflineFile) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *OfflineFile) GetStatus() OfflineFileStatus {
	if x != nil {
		return x.Status
	}
	return OfflineFileStatus_OFFLINE_INIT
}

func (x *OfflineFile) GetInfoHash() string {
	if x != nil {
		return x.InfoHash
	}
	return ""
}

func (x *OfflineFile) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *OfflineFile) GetAddTime() uint64 {
	if x != nil {
		return x.AddTime
	}
	return 0
}

func (x *OfflineFile) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *OfflineFile) GetPercendDone() float64 {
	if x != nil {
		return x.PercendDone
	}
	return 0
}

func (x *OfflineFile) GetPeers() uint64 {
	if x != nil {
		return x.Peers
	}
	return 0
}

type OfflineStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Quota         uint32                 `protobuf:"varint,1,opt,name=quota,proto3" json:"quota,omitempty"`
	Total         uint32                 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OfflineStatus) Reset() {
	*x = OfflineStatus{}
	mi := &file_clouddrive_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OfflineStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OfflineStatus) ProtoMessage() {}

func (x *OfflineStatus) ProtoReflect() protoreflect.Message {
	mi := &file_clouddrive_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OfflineStatus.ProtoReflect.Descriptor instead.
func (*OfflineStatus) Descriptor() ([]byte, []int) {
	return file_clouddrive_proto_rawDescGZIP(), []int{14}
}

func (x *OfflineStatus) GetQuota() uint32 {
	if x != nil {
		return x.Quota
	}
	return 0
}

func (x *OfflineStatus) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type OfflineFileListResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OfflineFiles  []*OfflineFile         `protobuf:"bytes,1,rep,name=offlineFiles,proto3" json:"offlineFiles,omitempty"`
	Status        *OfflineStatus         `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OfflineFileListResult) Reset() {
	*x = OfflineFileListResult{}
	mi := &file_clouddrive_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OfflineFileListResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OfflineFileListResult) ProtoMessage() {}

func (x *OfflineFileListResult) ProtoReflect() protoreflect.Message {
	mi := &file_clouddrive_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OfflineFileListResult.ProtoReflect.Descriptor instead.
func (*OfflineFileListResult) Descriptor() ([]byte, []int) {
	return file_clouddrive_proto_rawDescGZIP(), []int{15}
}

func (x *OfflineFileListResult) GetOfflineFiles() []*OfflineFile {
	if x != nil {
		return x.OfflineFiles
	}
	return nil
}

func (x *OfflineFileListResult) GetStatus() *OfflineStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type GetDownloadUrlPathRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Preview       bool                   `protobuf:"varint,2,opt,name=preview,proto3" json:"preview,omitempty"`
	LazyRead      bool                   `protobuf:"varint,3,opt,name=lazy_read,json=lazyRead,proto3" json:"lazy_read,omitempty"`
	GetDirectUrl  bool                   `protobuf:"varint,4,opt,name=get_direct_url,json=getDirectUrl,proto3" json:"get_direct_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDownloadUrlPathRequest) Reset() {
	*x = GetDownloadUrlPathRequest{}
	mi := &file_clouddrive_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDownloadUrlPathRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDownloadUrlPathRequest) ProtoMessage() {}

func (x *GetDownloadUrlPathRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clouddrive_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDownloadUrlPathRequest.ProtoReflect.Descriptor instead.
func (*GetDownloadUrlPathRequest) Descriptor() ([]byte, []int) {
	return file_clouddrive_proto_rawDescGZIP(), []int{16}
}

func (x *GetDownloadUrlPathRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *GetDownloadUrlPathRequest) GetPreview() bool {
	if x != nil {
		return x.Preview
	}
	return false
}

func (x *GetDownloadUrlPathRequest) GetLazyRead() bool {
	if x != nil {
		return x.LazyRead
	}
	return false
}

func (x *GetDownloadUrlPathRequest) GetGetDirectUrl() bool {
	if x != nil {
		return x.GetDirectUrl
	}
	return false
}

type DownloadUrlPathInfo struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	DownloadUrlPath   string                 `protobuf:"bytes,1,opt,name=downloadUrlPath,proto3" json:"downloadUrlPath,omitempty"`
	ExpiresIn         *uint64                `protobuf:"varint,2,opt,name=expiresIn,proto3,oneof" json:"expiresIn,omitempty"`
	DirectUrl         *string                `protobuf:"bytes,3,opt,name=directUrl,proto3,oneof" json:"directUrl,omitempty"`
	UserAgent         *string                `protobuf:"bytes,4,opt,name=userAgent,proto3,oneof" json:"userAgent,omitempty"`
	AdditionalHeaders map[string]string      `protobuf:"bytes,5,rep,name=additionalHeaders,proto3" json:"additionalHeaders,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DownloadUrlPathInfo) Reset() {
	*x = DownloadUrlPathInfo{}
	mi := &file_clouddrive_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadUrlPathInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadUrlPathInfo) ProtoMessage() {}

func (x *DownloadUrlPathInfo) ProtoReflect() protoreflect.Message {
	mi := &file_clouddrive_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadUrlPathInfo.ProtoReflect.Descriptor instead.
func (*DownloadUrlPathInfo) Descriptor() ([]byte, []int) {
	return file_clouddrive_proto_rawDescGZIP(), []int{17}
}

func (x *DownloadUrlPathInfo) GetDownloadUrlPath() string {
	if x != nil {
		return x.DownloadUrlPath
	}
	return ""
}

func (x *DownloadUrlPathInfo) GetExpiresIn() uint64 {
	if x != nil && x.ExpiresIn != nil {
		return *x.ExpiresIn
	}
	return 0
}

func (x *DownloadUrlPathInfo) GetDirectUrl() string {
	if x != nil && x.DirectUrl != nil {
		return *x.DirectUrl
	}
	return ""
}

func (x *DownloadUrlPathInfo) GetUserAgent() string {
	if x != nil && x.UserAgent != nil {
		return *x.UserAgent
	}
	return ""
}

func (x *DownloadUrlPathInfo) GetAdditionalHeaders() map[string]string {
	if x != nil {
		return x.AdditionalHeaders
	}
	return nil
}

var File_clouddrive_proto protoreflect.FileDescriptor

const file_clouddrive_proto_rawDesc = "" +
	"\n" +
	"\x10clouddrive.proto\x12\n" +
	"clouddrive\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"#\n" +
	"\vStringValue\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"\xd9\x01\n" +
	"\x14CloudDriveSystemInfo\x12\x18\n" +
	"\aIsLogin\x18\x01 \x01(\bR\aIsLogin\x12\x1a\n" +
	"\bUserName\x18\x02 \x01(\tR\bUserName\x12 \n" +
	"\vSystemReady\x18\x03 \x01(\bR\vSystemReady\x12)\n" +
	"\rSystemMessage\x18\x04 \x01(\tH\x00R\rSystemMessage\x88\x01\x01\x12\x1f\n" +
	"\bhasError\x18\x05 \x01(\bH\x01R\bhasError\x88\x01\x01B\x10\n" +
	"\x0e_SystemMessageB\v\n" +
	"\t_hasError\"\xfe\x01\n" +
	"\x10TokenPermissions\x12\x1d\n" +
	"\n" +
	"allow_list\x18\x01 \x01(\bR\tallowList\x12.\n" +
	"\x13allow_create_folder\x18\x04 \x01(\bR\x11allowCreateFolder\x12\x1d\n" +
	"\n" +
	"allow_read\x18\a \x01(\bR\tallowRead\x12;\n" +
	"\x1aallow_add_offline_download\x18\x10 \x01(\bR\x17allowAddOfflineDownload\x12?\n" +
	"\x1callow_list_offline_downloads\x18\x11 \x01(\bR\x19allowListOfflineDownloads\"\xd3\x01\n" +
	"\tTokenInfo\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x18\n" +
	"\arootDir\x18\x02 \x01(\tR\arootDir\x12>\n" +
	"\vpermissions\x18\x03 \x01(\v2\x1c.clouddrive.TokenPermissionsR\vpermissions\x12\"\n" +
	"\n" +
	"expires_in\x18\x04 \x01(\x04H\x00R\texpiresIn\x88\x01\x01\x12#\n" +
	"\rfriendly_name\x18\x05 \x01(\tR\ffriendlyNameB\r\n" +
	"\v_expires_in\"[\n" +
	"\vFileRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12'\n" +
	"\fforceRefresh\x18\x02 \x01(\bH\x00R\fforceRefresh\x88\x01\x01B\x0f\n" +
	"\r_forceRefresh\"}\n" +
	"\x13FileOperationResult\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\"\n" +
	"\ferrorMessage\x18\x02 \x01(\tR\ferrorMessage\x12(\n" +
	"\x0fresultFilePaths\x18\x03 \x03(\tR\x0fresultFilePaths\"\x99\x01\n" +
	"\x15AddOfflineFileRequest\x12\x12\n" +
	"\x04urls\x18\x01 \x01(\tR\x04urls\x12\x1a\n" +
	"\btoFolder\x18\x02 \x01(\tR\btoFolder\x127\n" +
	"\x14checkFolderAfterSecs\x18\x03 \x01(\x04H\x00R\x14checkFolderAfterSecs\x88\x01\x01B\x17\n" +
	"\x15_checkFolderAfterSecs\"\x86\x01\n" +
	"\x12ListSubFileRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\"\n" +
	"\fforceRefresh\x18\x02 \x01(\bR\fforceRefresh\x12'\n" +
	"\fcheckExpires\x18\x03 \x01(\bH\x00R\fcheckExpires\x88\x01\x01B\x0f\n" +
	"\r_checkExpires\"G\n" +
	"\rSubFilesReply\x126\n" +
	"\bsubFiles\x18\x01 \x03(\v2\x1a.clouddrive.CloudDriveFileR\bsubFiles\"K\n" +
	"\x15FindFileByPathRequest\x12\x1e\n" +
	"\n" +
	"parentPath\x18\x01 \x01(\tR\n" +
	"parentPath\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"U\n" +
	"\x13CreateFolderRequest\x12\x1e\n" +
	"\n" +
	"parentPath\x18\x01 \x01(\tR\n" +
	"parentPath\x12\x1e\n" +
	"\n" +
	"folderName\x18\x02 \x01(\tR\n" +
	"folderName\"\x8f\x01\n" +
	"\x12CreateFolderResult\x12@\n" +
	"\rfolderCreated\x18\x01 \x01(\v2\x1a.clouddrive.CloudDriveFileR\rfolderCreated\x127\n" +
	"\x06result\x18\x02 \x01(\v2\x1f.clouddrive.FileOperationResultR\x06result\"\xaf\x05\n" +
	"\x0eCloudDriveFile\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\"\n" +
	"\ffullPathName\x18\x03 \x01(\tR\ffullPathName\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\x12?\n" +
	"\bfileType\x18\x05 \x01(\x0e2#.clouddrive.CloudDriveFile.FileTypeR\bfileType\x12:\n" +
	"\n" +
	"createTime\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x128\n" +
	"\twriteTime\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\twriteTime\x12 \n" +
	"\visDirectory\x18\x1e \x01(\bR\visDirectory\x12\x16\n" +
	"\x06isRoot\x18\x1f \x01(\bR\x06isRoot\x12 \n" +
	"\visCloudRoot\x18  \x01(\bR\visCloudRoot\x12*\n" +
	"\x10isCloudDirectory\x18! \x01(\bR\x10isCloudDirectory\x12 \n" +
	"\visCloudFile\x18\" \x01(\bR\visCloudFile\x12\x18\n" +
	"\aisLocal\x18% \x01(\bR\aisLocal\x12.\n" +
	"\x12canOfflineDownload\x18B \x01(\bR\x12canOfflineDownload\x12J\n" +
	" supportOfflineDownloadManagement\x18K \x01(\bR supportOfflineDownloadManagement\x12\x1a\n" +
	"\breadOnly\x18P \x01(\bR\breadOnly\".\n" +
	"\bFileType\x12\r\n" +
	"\tDirectory\x10\x00\x12\b\n" +
	"\x04File\x10\x01\x12\t\n" +
	"\x05Other\x10\x02\"\xa1\x02\n" +
	"\vOfflineFile\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x04R\x04size\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x125\n" +
	"\x06status\x18\x04 \x01(\x0e2\x1d.clouddrive.OfflineFileStatusR\x06status\x12\x1a\n" +
	"\binfoHash\x18\x05 \x01(\tR\binfoHash\x12\x16\n" +
	"\x06fileId\x18\x06 \x01(\tR\x06fileId\x12\x19\n" +
	"\badd_time\x18\a \x01(\x04R\aaddTime\x12\x1a\n" +
	"\bparentId\x18\b \x01(\tR\bparentId\x12 \n" +
	"\vpercendDone\x18\t \x01(\x01R\vpercendDone\x12\x14\n" +
	"\x05peers\x18\n" +
	" \x01(\x04R\x05peers\";\n" +
	"\rOfflineStatus\x12\x14\n" +
	"\x05quota\x18\x01 \x01(\rR\x05quota\x12\x14\n" +
	"\x05total\x18\x02 \x01(\rR\x05total\"\x87\x01\n" +
	"\x15OfflineFileListResult\x12;\n" +
	"\fofflineFiles\x18\x01 \x03(\v2\x17.clouddrive.OfflineFileR\fofflineFiles\x121\n" +
	"\x06status\x18\x02 \x01(\v2\x19.clouddrive.OfflineStatusR\x06status\"\x8c\x01\n" +
	"\x19GetDownloadUrlPathRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x18\n" +
	"\apreview\x18\x02 \x01(\bR\apreview\x12\x1b\n" +
	"\tlazy_read\x18\x03 \x01(\bR\blazyRead\x12$\n" +
	"\x0eget_direct_url\x18\x04 \x01(\bR\fgetDirectUrl\"\xfe\x02\n" +
	"\x13DownloadUrlPathInfo\x12(\n" +
	"\x0fdownloadUrlPath\x18\x01 \x01(\tR\x0fdownloadUrlPath\x12!\n" +
	"\texpiresIn\x18\x02 \x01(\x04H\x00R\texpiresIn\x88\x01\x01\x12!\n" +
	"\tdirectUrl\x18\x03 \x01(\tH\x01R\tdirectUrl\x88\x01\x01\x12!\n" +
	"\tuserAgent\x18\x04 \x01(\tH\x02R\tuserAgent\x88\x01\x01\x12d\n" +
	"\x11additionalHeaders\x18\x05 \x03(\v26.clouddrive.DownloadUrlPathInfo.AdditionalHeadersEntryR\x11additionalHeaders\x1aD\n" +
	"\x16AdditionalHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\f\n" +
	"\n" +
	"_expiresInB\f\n" +
	"\n" +
	"_directUrlB\f\n" +
	"\n" +
	"_userAgent*|\n" +
	"\x11OfflineFileStatus\x12\x10\n" +
	"\fOFFLINE_INIT\x10\x00\x12\x17\n" +
	"\x13OFFLINE_DOWNLOADING\x10\x01\x12\x14\n" +
	"\x10OFFLINE_FINISHED\x10\x02\x12\x11\n" +
	"\rOFFLINE_ERROR\x10\x03\x12\x13\n" +
	"\x0fOFFLINE_UNKNOWN\x10\x042\x9a\x05\n" +
	"\x11CloudDriveFileSrv\x12I\n" +
	"\rGetSystemInfo\x12\x16.google.protobuf.Empty\x1a .clouddrive.CloudDriveSystemInfo\x12A\n" +
	"\x0fGetApiTokenInfo\x12\x17.clouddrive.StringValue\x1a\x15.clouddrive.TokenInfo\x12J\n" +
	"\vGetSubFiles\x12\x1e.clouddrive.ListSubFileRequest\x1a\x19.clouddrive.SubFilesReply0\x01\x12O\n" +
	"\x0eFindFileByPath\x12!.clouddrive.FindFileByPathRequest\x1a\x1a.clouddrive.CloudDriveFile\x12O\n" +
	"\fCreateFolder\x12\x1f.clouddrive.CreateFolderRequest\x1a\x1e.clouddrive.CreateFolderResult\x12U\n" +
	"\x0fAddOfflineFiles\x12!.clouddrive.AddOfflineFileRequest\x1a\x1f.clouddrive.FileOperationResult\x12T\n" +
	"\x16ListOfflineFilesByPath\x12\x17.clouddrive.FileRequest\x1a!.clouddrive.OfflineFileListResult\x12\\\n" +
	"\x12GetDownloadUrlPath\x12%.clouddrive.GetDownloadUrlPathRequest\x1a\x1f.clouddrive.DownloadUrlPathInfoB0Z.javboss/internal/clouddrive/proto;clouddrivepbb\x06proto3"

var (
	file_clouddrive_proto_rawDescOnce sync.Once
	file_clouddrive_proto_rawDescData []byte
)

func file_clouddrive_proto_rawDescGZIP() []byte {
	file_clouddrive_proto_rawDescOnce.Do(func() {
		file_clouddrive_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_clouddrive_proto_rawDesc), len(file_clouddrive_proto_rawDesc)))
	})
	return file_clouddrive_proto_rawDescData
}

var file_clouddrive_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_clouddrive_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_clouddrive_proto_goTypes = []any{
	(OfflineFileStatus)(0),            // 0: clouddrive.OfflineFileStatus
	(CloudDriveFile_FileType)(0),      // 1: clouddrive.CloudDriveFile.FileType
	(*StringValue)(nil),               // 2: clouddrive.StringValue
	(*CloudDriveSystemInfo)(nil),      // 3: clouddrive.CloudDriveSystemInfo
	(*TokenPermissions)(nil),          // 4: clouddrive.TokenPermissions
	(*TokenInfo)(nil),                 // 5: clouddrive.TokenInfo
	(*FileRequest)(nil),               // 6: clouddrive.FileRequest
	(*FileOperationResult)(nil),       // 7: clouddrive.FileOperationResult
	(*AddOfflineFileRequest)(nil),     // 8: clouddrive.AddOfflineFileRequest
	(*ListSubFileRequest)(nil),        // 9: clouddrive.ListSubFileRequest
	(*SubFilesReply)(nil),             // 10: clouddrive.SubFilesReply
	(*FindFileByPathRequest)(nil),     // 11: clouddrive.FindFileByPathRequest
	(*CreateFolderRequest)(nil),       // 12: clouddrive.CreateFolderRequest
	(*CreateFolderResult)(nil),        // 13: clouddrive.CreateFolderResult
	(*CloudDriveFile)(nil),            // 14: clouddrive.CloudDriveFile
	(*OfflineFile)(nil),               // 15: clouddrive.OfflineFile
	(*OfflineStatus)(nil),             // 16: clouddrive.OfflineStatus
	(*OfflineFileListResult)(nil),     // 17: clouddrive.OfflineFileListResult
	(*GetDownloadUrlPathRequest)(nil), // 18: clouddrive.GetDownloadUrlPathRequest
	(*DownloadUrlPathInfo)(nil),       // 19: clouddrive.DownloadUrlPathInfo
	nil,                               // 20: clouddrive.DownloadUrlPathInfo.AdditionalHeadersEntry
	(*timestamppb.Timestamp)(nil),     // 21: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),             // 22: google.protobuf.Empty
}
var file_clouddrive_proto_depIdxs = []int32{
	4,  // 0: clouddrive.TokenInfo.permissions:type_name -> clouddrive.TokenPermissions
	14, // 1: clouddrive.SubFilesReply.subFiles:type_name -> clouddrive.CloudDriveFile
	14, // 2: clouddrive.CreateFolderResult.folderCreated:type_name -> clouddrive.CloudDriveFile
	7,  // 3: clouddrive.CreateFolderResult.result:type_name -> clouddrive.FileOperationResult
	1,  // 4: clouddrive.CloudDriveFile.fileType:type_name -> clouddrive.CloudDriveFile.FileType
	21, // 5: clouddrive.CloudDriveFile.createTime:type_name -> google.protobuf.Timestamp
	21, // 6: clouddrive.CloudDriveFile.writeTime:type_name -> google.protobuf.Timestamp
	0,  // 7: clouddrive.OfflineFile.status:type_name -> clouddrive.OfflineFileStatus
	15, // 8: clouddrive.OfflineFileListResult.offlineFiles:type_name -> clouddrive.OfflineFile
	16, // 9: clouddrive.OfflineFileListResult.status:type_name -> clouddrive.OfflineStatus
	20, // 10: clouddrive.DownloadUrlPathInfo.additionalHeaders:type_name -> clouddrive.DownloadUrlPathInfo.AdditionalHeadersEntry
	22, // 11: clouddrive.CloudDriveFileSrv.GetSystemInfo:input_type -> google.protobuf.Empty
	2,  // 12: clouddrive.CloudDriveFileSrv.GetApiTokenInfo:input_type -> clouddrive.StringValue
	9,  // 13: clouddrive.CloudDriveFileSrv.GetSubFiles:input_type -> clouddrive.ListSubFileRequest
	11, // 14: clouddrive.CloudDriveFileSrv.FindFileByPath:input_type -> clouddrive.FindFileByPathRequest
	12, // 15: clouddrive.CloudDriveFileSrv.CreateFolder:input_type -> clouddrive.CreateFolderRequest
	8,  // 16: clouddrive.CloudDriveFileSrv.AddOfflineFiles:input_type -> clouddrive.AddOfflineFileRequest
	6,  // 17: clouddrive.CloudDriveFileSrv.ListOfflineFilesByPath:input_type -> clouddrive.FileRequest
	18, // 18: clouddrive.CloudDriveFileSrv.GetDownloadUrlPath:input_type -> clouddrive.GetDownloadUrlPathRequest
	3,  // 19: clouddrive.CloudDriveFileSrv.GetSystemInfo:output_type -> clouddrive.CloudDriveSystemInfo
	5,  // 20: clouddrive.CloudDriveFileSrv.GetApiTokenInfo:output_type -> clouddrive.TokenInfo
	10, // 21: clouddrive.CloudDriveFileSrv.GetSubFiles:output_type -> clouddrive.SubFilesReply
	14, // 22: clouddrive.CloudDriveFileSrv.FindFileByPath:output_type -> clouddrive.CloudDriveFile
	13, // 23: clouddrive.CloudDriveFileSrv.CreateFolder:output_type -> clouddrive.CreateFolderResult
	7,  // 24: clouddrive.CloudDriveFileSrv.AddOfflineFiles:output_type -> clouddrive.FileOperationResult
	17, // 25: clouddrive.CloudDriveFileSrv.ListOfflineFilesByPath:output_type -> clouddrive.OfflineFileListResult
	19, // 26: clouddrive.CloudDriveFileSrv.GetDownloadUrlPath:output_type -> clouddrive.DownloadUrlPathInfo
	19, // [19:27] is the sub-list for method output_type
	11, // [11:19] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_clouddrive_proto_init() }
func file_clouddrive_proto_init() {
	if File_clouddrive_proto != nil {
		return
	}
	file_clouddrive_proto_msgTypes[1].OneofWrappers = []any{}
	file_clouddrive_proto_msgTypes[3].OneofWrappers = []any{}
	file_clouddrive_proto_msgTypes[4].OneofWrappers = []any{}
	file_clouddrive_proto_msgTypes[6].OneofWrappers = []any{}
	file_clouddrive_proto_msgTypes[7].OneofWrappers = []any{}
	file_clouddrive_proto_msgTypes[17].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_clouddrive_proto_rawDesc), len(file_clouddrive_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_clouddrive_proto_goTypes,
		DependencyIndexes: file_clouddrive_proto_depIdxs,
		EnumInfos:         file_clouddrive_proto_enumTypes,
		MessageInfos:      file_clouddrive_proto_msgTypes,
	}.Build()
	File_clouddrive_proto = out.File
	file_clouddrive_proto_goTypes = nil
	file_clouddrive_proto_depIdxs = nil
}
